// 외형(appearance) 프롬프트 — VPN 없이 오프라인 생성용. 3090 Qwen 게이트웨이 대역으로 Claude(비전 모델)가
// 실제 소스 그림을 직접 보고 작성. 게이트웨이 최소화 규칙(qwen-prompt-server/prompts.py)과 동일:
//   색상 몇 개 + 형태 카테고리만, 캐릭터명/구도/뷰/배경/포즈 언급 금지.
// generateOffline.ts가 이 값을 job.prompt로 주입 → Orchestrator.getAppearance가 게이트웨이 호출 없이 그대로 사용.
// 배경(background)은 AI 생성 자체를 안 하므로 없음.
export const APPEARANCE = {
  // ---- 몬스터 24 ----
  goomba: "brown, dark brown, round mushroom-shaped creature with a grumpy face, 2D platformer game sprite",
  koopa: "green, brown shell, small round turtle-like creature, 2D platformer game sprite",
  "buzzy-beetle": "dark gray, black, round dome-shelled beetle creature, 2D platformer game sprite",
  spiny: "red, dark red, round spiky ball creature with an angry face, 2D platformer game sprite",
  piranha: "red, green, yellow spots, flower-headed plant creature on a stem, 2D platformer game sprite",
  boo: "white, pale gray, round soft ghost blob, 2D platformer game sprite",
  "bob-omb": "black, yellow, round bomb-shaped creature with small feet, 2D platformer game sprite",
  "chain-chomp": "black, white teeth, gray, round spiky ball creature, 2D platformer game sprite",
  lakitu: "white, pale gray, fluffy round cloud creature, 2D platformer game sprite",
  "hammer-bro": "dark gray, teal, orange, upright humanoid creature, 2D platformer game sprite",
  "straight-shooter": "blue, tan, simple upright humanoid creature, 2D platformer game sprite",
  "tracker-homing": "purple, round floating blob creature, 2D platformer game sprite",
  "king-splitter": "green, round soft blob creature, 2D platformer game sprite",
  "teleport-boss": "purple, tall upright humanoid creature with a spiky head, 2D platformer game sprite",
  creeper: "green, tall blocky upright humanoid creature, 2D platformer game sprite",
  zombie: "green, dark, simple upright humanoid creature, 2D platformer game sprite",
  spider: "black, dark gray, round-bodied many-legged creature, 2D platformer game sprite",
  enderman: "black, very tall thin upright humanoid creature, 2D platformer game sprite",
  "trampoline-ball": "green, round bouncy ball creature, 2D platformer game sprite",
  "shy-fleer": "pink, round soft blob creature, 2D platformer game sprite",
  "hop-syncer": "cyan, teal, round blob creature, 2D platformer game sprite",
  enrager: "brown, orange, red, round creature with an angry face, 2D platformer game sprite",
  "pushable-crate-mob": "brown, square wooden crate, 2D platformer game sprite",
  "boss-big": "orange, dark red, large wide upright humanoid creature, 2D platformer game sprite",

  // ---- 블록 29 ----
  brick: "brown, square block, 2D platformer game sprite",
  "question-block": "golden yellow, square block with a small round mark, 2D platformer game sprite",
  "ice-block": "cyan, pale blue, translucent square ice block, 2D platformer game sprite",
  "breakable-block": "brown, dark, cracked square stone block, 2D platformer game sprite",
  "falling-platform": "brown, wide wooden platform block, 2D platformer game sprite",
  "moving-platform": "blue gray, wide metal platform block, 2D platformer game sprite",
  "pendulum-hazard": "dark red, dark gray, round spiked hazard, 2D platformer game sprite",
  "spin-fireball": "orange, red, round fiery ball, 2D platformer game sprite",
  "charge-block": "gray, square stone block with a red stripe, 2D platformer game sprite",
  spring: "red, coiled spring, 2D platformer game sprite",
  "updraft-fan": "light blue, cyan, round fan block, 2D platformer game sprite",
  "conveyor-belt": "gray, dark gray, wide metal conveyor block, 2D platformer game sprite",
  "dash-panel": "orange, square panel with an arrow, 2D platformer game sprite",
  "cannon-straight": "dark gray, black, tall metal cannon, 2D platformer game sprite",
  "cannon-homing": "dark gray, red, tall metal cannon, 2D platformer game sprite",
  "switch-block-on": "bright purple, glowing square block, 2D platformer game sprite",
  "switch-block-off": "dark purple, dim square block, 2D platformer game sprite",
  "blink-block": "teal, green, square block, 2D platformer game sprite",
  "hidden-block": "neutral gray, plain square block, 2D platformer game sprite",
  "spike-row": "gray, dark, row of metal spikes, 2D platformer game sprite",
  icicle: "pale blue, white, pointed icicle shape, 2D platformer game sprite",
  "corner-wall": "gray, square stone wall block, 2D platformer game sprite",
  "ride-start": "green, wide platform block, 2D platformer game sprite",
  "ride-oneway": "blue, thin wide platform block, 2D platformer game sprite",
  "breakblocks-block": "dark gray, cracked heavy square block, 2D platformer game sprite",
  "slope-floor-asc": "brown, green top edge, right-triangle slope block, 2D platformer game sprite",
  "slope-floor-desc": "brown, green top edge, right-triangle slope block, 2D platformer game sprite",
  "slope-ceil-desc": "blue, gray, right-triangle wedge block, 2D platformer game sprite",
  "slope-ceil-asc": "blue, gray, right-triangle wedge block, 2D platformer game sprite",

  // ---- 아이템 2 ----
  "item-giant-mushroom": "red, white spots, tan stem, round mushroom, 2D platformer game sprite",
  "item-speed-boost": "golden yellow, glowing lightning bolt shape, 2D platformer game sprite",

  // ---- 아바타 16 (캐릭터명 없이 색상+형태만 — 이름 유출/환각 방지) ----
  "avatar-mario": "red cap, red shirt, blue overalls, tan skin, brown mustache, round-headed humanoid, 2D platformer game sprite",
  "avatar-luigi": "green cap, green shirt, purple overalls, tan skin, brown mustache, round-headed humanoid, 2D platformer game sprite",
  "avatar-princess": "pink dress, blonde hair, small crown, tan skin, humanoid, 2D platformer game sprite",
  "avatar-toad": "white and red spotted mushroom cap, tan skin, small humanoid, 2D platformer game sprite",
  "avatar-gorilla": "brown fur, tan face, red tie, stocky ape-like humanoid, 2D platformer game sprite",
  "avatar-mouse": "gray fur, pink cheeks, big round ears, mouse-like creature, 2D platformer game sprite",
  "avatar-goose": "white body, orange beak and feet, long-necked bird, 2D platformer game sprite",
  "avatar-croc": "green scales, cream belly, long-snouted crocodile-like humanoid, 2D platformer game sprite",
  "avatar-steve": "blue shirt, dark pants, brown hair, tan skin, blocky humanoid, 2D platformer game sprite",
  "avatar-creeper": "green, tall blocky upright humanoid, 2D platformer game sprite",
  "avatar-speedster": "blue body, white gloves, tan skin, spiky-headed humanoid, 2D platformer game sprite",
  "avatar-kirby": "pink, red feet, round soft ball creature, 2D platformer game sprite",
  "avatar-robot": "gray metal, blue visor, blocky humanoid, 2D platformer game sprite",
  "avatar-turtleninja": "green skin, orange headband, brown shell, humanoid, 2D platformer game sprite",
  "avatar-knight": "gray silver armor, full helmet, armored humanoid, 2D platformer game sprite",
  "avatar-pirate": "black tricorn hat, dark coat, tan skin, humanoid, 2D platformer game sprite",
};
